# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeqGenMainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1290, 879)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 501, 481))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 201, 303))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.spinBox_NX = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_NX.setMaximum(999999999)
        self.spinBox_NX.setSingleStep(1)
        self.spinBox_NX.setProperty("value", 1)
        self.spinBox_NX.setObjectName("spinBox_NX")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_NX)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox_NR = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_NR.setMaximum(999999999)
        self.spinBox_NR.setSingleStep(16)
        self.spinBox_NR.setProperty("value", 256)
        self.spinBox_NR.setObjectName("spinBox_NR")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_NR)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox_N1 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_N1.setMaximum(999999999)
        self.spinBox_N1.setSingleStep(16)
        self.spinBox_N1.setProperty("value", 256)
        self.spinBox_N1.setObjectName("spinBox_N1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_N1)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.spinBox_N2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_N2.setMaximum(999999999)
        self.spinBox_N2.setSingleStep(16)
        self.spinBox_N2.setProperty("value", 256)
        self.spinBox_N2.setObjectName("spinBox_N2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox_N2)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.spinBox_S1 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_S1.setMaximum(999999999)
        self.spinBox_S1.setSingleStep(16)
        self.spinBox_S1.setProperty("value", 256)
        self.spinBox_S1.setObjectName("spinBox_S1")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_S1)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.spinBox_S2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_S2.setMaximum(999999999)
        self.spinBox_S2.setSingleStep(16)
        self.spinBox_S2.setProperty("value", 256)
        self.spinBox_S2.setObjectName("spinBox_S2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox_S2)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.spinBox_DU = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_DU.setMaximum(999999999)
        self.spinBox_DU.setSingleStep(1)
        self.spinBox_DU.setProperty("value", 5)
        self.spinBox_DU.setObjectName("spinBox_DU")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_DU)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.spinBox_TR = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_TR.setMaximum(999999999)
        self.spinBox_TR.setSingleStep(100)
        self.spinBox_TR.setProperty("value", 200)
        self.spinBox_TR.setObjectName("spinBox_TR")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBox_TR)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.spinBox_DW = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_DW.setMaximum(999999999)
        self.spinBox_DW.setSingleStep(1)
        self.spinBox_DW.setProperty("value", 10)
        self.spinBox_DW.setObjectName("spinBox_DW")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spinBox_DW)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.doubleSpinBox_SW = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_SW.setDecimals(4)
        self.doubleSpinBox_SW.setMinimum(0.0)
        self.doubleSpinBox_SW.setMaximum(10000000.0)
        self.doubleSpinBox_SW.setProperty("value", 5.0)
        self.doubleSpinBox_SW.setObjectName("doubleSpinBox_SW")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_SW)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.doubleSpinBox_OF = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox_OF.setDecimals(4)
        self.doubleSpinBox_OF.setMinimum(-1e+20)
        self.doubleSpinBox_OF.setMaximum(1e+20)
        self.doubleSpinBox_OF.setProperty("value", 0.0)
        self.doubleSpinBox_OF.setObjectName("doubleSpinBox_OF")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_OF)
        self.textEdit_comments = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_comments.setGeometry(QtCore.QRect(260, 270, 201, 91))
        self.textEdit_comments.setObjectName("textEdit_comments")
        self.label_42 = QtWidgets.QLabel(self.groupBox)
        self.label_42.setGeometry(QtCore.QRect(320, 250, 71, 20))
        self.label_42.setObjectName("label_42")
        self.listWidget_G_read = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_G_read.setGeometry(QtCore.QRect(30, 400, 41, 71))
        self.listWidget_G_read.setSelectionRectVisible(True)
        self.listWidget_G_read.setObjectName("listWidget_G_read")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_G_read.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_G_read.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_G_read.addItem(item)
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        self.label_40.setGeometry(QtCore.QRect(110, 340, 61, 73))
        self.label_40.setObjectName("label_40")
        self.listWidget_G_encode1 = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_G_encode1.setGeometry(QtCore.QRect(120, 400, 41, 71))
        self.listWidget_G_encode1.setSelectionRectVisible(True)
        self.listWidget_G_encode1.setObjectName("listWidget_G_encode1")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_G_encode1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_G_encode1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_G_encode1.addItem(item)
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        self.label_41.setGeometry(QtCore.QRect(210, 340, 61, 73))
        self.label_41.setObjectName("label_41")
        self.listWidget_G_encode2 = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_G_encode2.setGeometry(QtCore.QRect(210, 400, 41, 71))
        self.listWidget_G_encode2.setSelectionRectVisible(True)
        self.listWidget_G_encode2.setObjectName("listWidget_G_encode2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_G_encode2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_G_encode2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_G_encode2.addItem(item)
        self.label_39 = QtWidgets.QLabel(self.groupBox)
        self.label_39.setGeometry(QtCore.QRect(30, 350, 51, 59))
        self.label_39.setObjectName("label_39")
        self.textBrowser_history = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_history.setGeometry(QtCore.QRect(530, 20, 471, 192))
        self.textBrowser_history.setObjectName("textBrowser_history")
        self.tabWidget_ImageParams = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_ImageParams.setGeometry(QtCore.QRect(20, 500, 1271, 171))
        self.tabWidget_ImageParams.setObjectName("tabWidget_ImageParams")
        self.tab_SE = QtWidgets.QWidget()
        self.tab_SE.setObjectName("tab_SE")
        self.doubleSpinBox_SE_TE = QtWidgets.QDoubleSpinBox(self.tab_SE)
        self.doubleSpinBox_SE_TE.setGeometry(QtCore.QRect(70, 30, 100, 20))
        self.doubleSpinBox_SE_TE.setDecimals(4)
        self.doubleSpinBox_SE_TE.setMinimum(0.0)
        self.doubleSpinBox_SE_TE.setMaximum(10000000.0)
        self.doubleSpinBox_SE_TE.setProperty("value", 10.0)
        self.doubleSpinBox_SE_TE.setObjectName("doubleSpinBox_SE_TE")
        self.label_23 = QtWidgets.QLabel(self.tab_SE)
        self.label_23.setGeometry(QtCore.QRect(10, 30, 70, 20))
        self.label_23.setObjectName("label_23")
        self.checkBox_SE_is3D = QtWidgets.QCheckBox(self.tab_SE)
        self.checkBox_SE_is3D.setGeometry(QtCore.QRect(70, 60, 75, 16))
        self.checkBox_SE_is3D.setChecked(True)
        self.checkBox_SE_is3D.setObjectName("checkBox_SE_is3D")
        self.label_28 = QtWidgets.QLabel(self.tab_SE)
        self.label_28.setGeometry(QtCore.QRect(90, 100, 481, 20))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_SE)
        self.label_29.setGeometry(QtCore.QRect(110, 100, 591, 20))
        self.label_29.setObjectName("label_29")
        self.checkBox_SE_isUD_RFPulse90 = QtWidgets.QCheckBox(self.tab_SE)
        self.checkBox_SE_isUD_RFPulse90.setGeometry(QtCore.QRect(190, 60, 221, 16))
        self.checkBox_SE_isUD_RFPulse90.setObjectName("checkBox_SE_isUD_RFPulse90")
        self.checkBox_SE_isUD_RFPulse180 = QtWidgets.QCheckBox(self.tab_SE)
        self.checkBox_SE_isUD_RFPulse180.setGeometry(QtCore.QRect(190, 80, 241, 16))
        self.checkBox_SE_isUD_RFPulse180.setObjectName("checkBox_SE_isUD_RFPulse180")
        self.tabWidget_ImageParams.addTab(self.tab_SE, "")
        self.tab_GE = QtWidgets.QWidget()
        self.tab_GE.setObjectName("tab_GE")
        self.label_33 = QtWidgets.QLabel(self.tab_GE)
        self.label_33.setGeometry(QtCore.QRect(10, 30, 70, 20))
        self.label_33.setObjectName("label_33")
        self.doubleSpinBox_GE_TE = QtWidgets.QDoubleSpinBox(self.tab_GE)
        self.doubleSpinBox_GE_TE.setGeometry(QtCore.QRect(70, 30, 100, 20))
        self.doubleSpinBox_GE_TE.setDecimals(4)
        self.doubleSpinBox_GE_TE.setMinimum(0.0)
        self.doubleSpinBox_GE_TE.setMaximum(10000000.0)
        self.doubleSpinBox_GE_TE.setProperty("value", 10.0)
        self.doubleSpinBox_GE_TE.setObjectName("doubleSpinBox_GE_TE")
        self.checkBox_GE_is3D = QtWidgets.QCheckBox(self.tab_GE)
        self.checkBox_GE_is3D.setGeometry(QtCore.QRect(70, 60, 75, 16))
        self.checkBox_GE_is3D.setChecked(True)
        self.checkBox_GE_is3D.setObjectName("checkBox_GE_is3D")
        self.label_34 = QtWidgets.QLabel(self.tab_GE)
        self.label_34.setGeometry(QtCore.QRect(110, 100, 591, 20))
        self.label_34.setObjectName("label_34")
        self.checkBox_GE_isUD_RFPulse = QtWidgets.QCheckBox(self.tab_GE)
        self.checkBox_GE_isUD_RFPulse.setGeometry(QtCore.QRect(190, 60, 221, 16))
        self.checkBox_GE_isUD_RFPulse.setObjectName("checkBox_GE_isUD_RFPulse")
        self.tabWidget_ImageParams.addTab(self.tab_GE, "")
        self.tabWidget_Hardware = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_Hardware.setGeometry(QtCore.QRect(20, 680, 1271, 151))
        self.tabWidget_Hardware.setObjectName("tabWidget_Hardware")
        self.tab_Gradient = QtWidgets.QWidget()
        self.tab_Gradient.setObjectName("tab_Gradient")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_Gradient)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1245, 100))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_resistance_x = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_resistance_x.setDecimals(4)
        self.doubleSpinBox_resistance_x.setMinimum(0.0)
        self.doubleSpinBox_resistance_x.setMaximum(10000000.0)
        self.doubleSpinBox_resistance_x.setProperty("value", 1.0)
        self.doubleSpinBox_resistance_x.setObjectName("doubleSpinBox_resistance_x")
        self.gridLayout.addWidget(self.doubleSpinBox_resistance_x, 0, 7, 1, 1)
        self.doubleSpinBox_GZ = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_GZ.setDecimals(4)
        self.doubleSpinBox_GZ.setMaximum(10000000.0)
        self.doubleSpinBox_GZ.setProperty("value", 1.0)
        self.doubleSpinBox_GZ.setObjectName("doubleSpinBox_GZ")
        self.gridLayout.addWidget(self.doubleSpinBox_GZ, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 6, 1, 1)
        self.doubleSpinBox_MaxCurrent = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_MaxCurrent.setDecimals(0)
        self.doubleSpinBox_MaxCurrent.setMaximum(10000000.0)
        self.doubleSpinBox_MaxCurrent.setProperty("value", 10.0)
        self.doubleSpinBox_MaxCurrent.setObjectName("doubleSpinBox_MaxCurrent")
        self.gridLayout.addWidget(self.doubleSpinBox_MaxCurrent, 0, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 6, 1, 1)
        self.doubleSpinBox_GY = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_GY.setDecimals(4)
        self.doubleSpinBox_GY.setMaximum(10000000.0)
        self.doubleSpinBox_GY.setProperty("value", 1.0)
        self.doubleSpinBox_GY.setObjectName("doubleSpinBox_GY")
        self.gridLayout.addWidget(self.doubleSpinBox_GY, 1, 1, 1, 1)
        self.doubleSpinBox_MaxVoltage = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_MaxVoltage.setDecimals(0)
        self.doubleSpinBox_MaxVoltage.setMaximum(10000000.0)
        self.doubleSpinBox_MaxVoltage.setProperty("value", 20.0)
        self.doubleSpinBox_MaxVoltage.setObjectName("doubleSpinBox_MaxVoltage")
        self.gridLayout.addWidget(self.doubleSpinBox_MaxVoltage, 1, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.doubleSpinBox_GrampX = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_GrampX.setDecimals(0)
        self.doubleSpinBox_GrampX.setMinimum(0.0)
        self.doubleSpinBox_GrampX.setMaximum(10000000.0)
        self.doubleSpinBox_GrampX.setProperty("value", 300.0)
        self.doubleSpinBox_GrampX.setObjectName("doubleSpinBox_GrampX")
        self.gridLayout.addWidget(self.doubleSpinBox_GrampX, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 0, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.doubleSpinBox_GX = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_GX.setDecimals(4)
        self.doubleSpinBox_GX.setMinimum(0.0)
        self.doubleSpinBox_GX.setMaximum(10000000.0)
        self.doubleSpinBox_GX.setProperty("value", 1.0)
        self.doubleSpinBox_GX.setObjectName("doubleSpinBox_GX")
        self.gridLayout.addWidget(self.doubleSpinBox_GX, 0, 1, 1, 1)
        self.doubleSpinBox_GrampZ = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_GrampZ.setDecimals(0)
        self.doubleSpinBox_GrampZ.setMinimum(0.0)
        self.doubleSpinBox_GrampZ.setMaximum(10000000.0)
        self.doubleSpinBox_GrampZ.setProperty("value", 300.0)
        self.doubleSpinBox_GrampZ.setObjectName("doubleSpinBox_GrampZ")
        self.gridLayout.addWidget(self.doubleSpinBox_GrampZ, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.doubleSpinBox_GrampY = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_GrampY.setDecimals(0)
        self.doubleSpinBox_GrampY.setMinimum(0.0)
        self.doubleSpinBox_GrampY.setMaximum(10000000.0)
        self.doubleSpinBox_GrampY.setProperty("value", 300.0)
        self.doubleSpinBox_GrampY.setObjectName("doubleSpinBox_GrampY")
        self.gridLayout.addWidget(self.doubleSpinBox_GrampY, 1, 3, 1, 1)
        self.doubleSpinBox_resistance_z = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_resistance_z.setDecimals(4)
        self.doubleSpinBox_resistance_z.setMinimum(0.0)
        self.doubleSpinBox_resistance_z.setMaximum(10000000.0)
        self.doubleSpinBox_resistance_z.setProperty("value", 1.0)
        self.doubleSpinBox_resistance_z.setObjectName("doubleSpinBox_resistance_z")
        self.gridLayout.addWidget(self.doubleSpinBox_resistance_z, 2, 7, 1, 1)
        self.doubleSpinBox_resistance_y = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_resistance_y.setDecimals(4)
        self.doubleSpinBox_resistance_y.setMinimum(0.0)
        self.doubleSpinBox_resistance_y.setMaximum(10000000.0)
        self.doubleSpinBox_resistance_y.setProperty("value", 1.0)
        self.doubleSpinBox_resistance_y.setObjectName("doubleSpinBox_resistance_y")
        self.gridLayout.addWidget(self.doubleSpinBox_resistance_y, 1, 7, 1, 1)
        self.doubleSpinBox_GDA1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_GDA1.setDecimals(0)
        self.doubleSpinBox_GDA1.setMinimum(-10000000.0)
        self.doubleSpinBox_GDA1.setMaximum(10000000.0)
        self.doubleSpinBox_GDA1.setProperty("value", 0.0)
        self.doubleSpinBox_GDA1.setObjectName("doubleSpinBox_GDA1")
        self.gridLayout.addWidget(self.doubleSpinBox_GDA1, 0, 9, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 8, 1, 1)
        self.doubleSpinBox_GDA2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_GDA2.setDecimals(0)
        self.doubleSpinBox_GDA2.setMinimum(-10000000.0)
        self.doubleSpinBox_GDA2.setMaximum(10000000.0)
        self.doubleSpinBox_GDA2.setProperty("value", 0.0)
        self.doubleSpinBox_GDA2.setObjectName("doubleSpinBox_GDA2")
        self.gridLayout.addWidget(self.doubleSpinBox_GDA2, 1, 9, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 2, 8, 1, 1)
        self.doubleSpinBox_GDA3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_GDA3.setDecimals(0)
        self.doubleSpinBox_GDA3.setMinimum(-10000000.0)
        self.doubleSpinBox_GDA3.setMaximum(10000000.0)
        self.doubleSpinBox_GDA3.setProperty("value", 0.0)
        self.doubleSpinBox_GDA3.setObjectName("doubleSpinBox_GDA3")
        self.gridLayout.addWidget(self.doubleSpinBox_GDA3, 2, 9, 1, 1)
        self.tabWidget_Hardware.addTab(self.tab_Gradient, "")
        self.tab_RF = QtWidgets.QWidget()
        self.tab_RF.setObjectName("tab_RF")
        self.pushButton_RFpulse180 = QtWidgets.QPushButton(self.tab_RF)
        self.pushButton_RFpulse180.setGeometry(QtCore.QRect(174, 70, 111, 31))
        self.pushButton_RFpulse180.setObjectName("pushButton_RFpulse180")
        self.pushButton_RFpulse90 = QtWidgets.QPushButton(self.tab_RF)
        self.pushButton_RFpulse90.setGeometry(QtCore.QRect(174, 20, 111, 31))
        self.pushButton_RFpulse90.setObjectName("pushButton_RFpulse90")
        self.textBrowser_RFpulse90 = QtWidgets.QTextBrowser(self.tab_RF)
        self.textBrowser_RFpulse90.setGeometry(QtCore.QRect(290, 20, 681, 31))
        self.textBrowser_RFpulse90.setObjectName("textBrowser_RFpulse90")
        self.textBrowser_RFpulse180 = QtWidgets.QTextBrowser(self.tab_RF)
        self.textBrowser_RFpulse180.setGeometry(QtCore.QRect(290, 70, 681, 31))
        self.textBrowser_RFpulse180.setObjectName("textBrowser_RFpulse180")
        self.tabWidget_Hardware.addTab(self.tab_RF, "")
        self.pushButton_genSeq = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_genSeq.setGeometry(QtCore.QRect(660, 430, 161, 51))
        self.pushButton_genSeq.setObjectName("pushButton_genSeq")
        self.textBrowser_seq = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_seq.setGeometry(QtCore.QRect(530, 220, 471, 192))
        self.textBrowser_seq.setObjectName("textBrowser_seq")
        self.pushButton_ShowEventView = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ShowEventView.setGeometry(QtCore.QRect(840, 430, 161, 51))
        self.pushButton_ShowEventView.setWhatsThis("")
        self.pushButton_ShowEventView.setObjectName("pushButton_ShowEventView")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(250, 60, 258, 79))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.doubleSpinBox_FOVr = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.doubleSpinBox_FOVr.setDecimals(4)
        self.doubleSpinBox_FOVr.setMinimum(0.0)
        self.doubleSpinBox_FOVr.setMaximum(1e+20)
        self.doubleSpinBox_FOVr.setProperty("value", 6.4)
        self.doubleSpinBox_FOVr.setObjectName("doubleSpinBox_FOVr")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_FOVr)
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.doubleSpinBox_FOVe1 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.doubleSpinBox_FOVe1.setDecimals(4)
        self.doubleSpinBox_FOVe1.setMinimum(0.0)
        self.doubleSpinBox_FOVe1.setMaximum(1e+20)
        self.doubleSpinBox_FOVe1.setProperty("value", 6.4)
        self.doubleSpinBox_FOVe1.setObjectName("doubleSpinBox_FOVe1")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_FOVe1)
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.doubleSpinBox_FOVe2 = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.doubleSpinBox_FOVe2.setDecimals(4)
        self.doubleSpinBox_FOVe2.setMinimum(0.0)
        self.doubleSpinBox_FOVe2.setMaximum(1e+20)
        self.doubleSpinBox_FOVe2.setProperty("value", 6.4)
        self.doubleSpinBox_FOVe2.setObjectName("doubleSpinBox_FOVe2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_FOVe2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSaveSeq = QtWidgets.QAction(MainWindow)
        self.actionSaveSeq.setObjectName("actionSaveSeq")
        self.actionOpen_ini_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_ini_file.setObjectName("actionOpen_ini_file")
        self.actionSave_ini_file = QtWidgets.QAction(MainWindow)
        self.actionSave_ini_file.setObjectName("actionSave_ini_file")
        self.menuFile.addAction(self.actionSaveSeq)
        self.menuFile.addAction(self.actionOpen_ini_file)
        self.menuFile.addAction(self.actionSave_ini_file)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.listWidget_G_read.setCurrentRow(0)
        self.listWidget_G_encode1.setCurrentRow(1)
        self.listWidget_G_encode2.setCurrentRow(2)
        self.tabWidget_ImageParams.setCurrentIndex(1)
        self.tabWidget_Hardware.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spinBox_NX, self.spinBox_NR)
        MainWindow.setTabOrder(self.spinBox_NR, self.spinBox_N1)
        MainWindow.setTabOrder(self.spinBox_N1, self.spinBox_N2)
        MainWindow.setTabOrder(self.spinBox_N2, self.spinBox_S1)
        MainWindow.setTabOrder(self.spinBox_S1, self.spinBox_S2)
        MainWindow.setTabOrder(self.spinBox_S2, self.spinBox_DU)
        MainWindow.setTabOrder(self.spinBox_DU, self.spinBox_TR)
        MainWindow.setTabOrder(self.spinBox_TR, self.spinBox_DW)
        MainWindow.setTabOrder(self.spinBox_DW, self.doubleSpinBox_SW)
        MainWindow.setTabOrder(self.doubleSpinBox_SW, self.doubleSpinBox_OF)
        MainWindow.setTabOrder(self.doubleSpinBox_OF, self.tabWidget_ImageParams)
        MainWindow.setTabOrder(self.tabWidget_ImageParams, self.tabWidget_Hardware)
        MainWindow.setTabOrder(self.tabWidget_Hardware, self.doubleSpinBox_GX)
        MainWindow.setTabOrder(self.doubleSpinBox_GX, self.doubleSpinBox_GY)
        MainWindow.setTabOrder(self.doubleSpinBox_GY, self.doubleSpinBox_GZ)
        MainWindow.setTabOrder(self.doubleSpinBox_GZ, self.doubleSpinBox_GrampX)
        MainWindow.setTabOrder(self.doubleSpinBox_GrampX, self.doubleSpinBox_GrampY)
        MainWindow.setTabOrder(self.doubleSpinBox_GrampY, self.doubleSpinBox_GrampZ)
        MainWindow.setTabOrder(self.doubleSpinBox_GrampZ, self.doubleSpinBox_MaxCurrent)
        MainWindow.setTabOrder(self.doubleSpinBox_MaxCurrent, self.doubleSpinBox_MaxVoltage)
        MainWindow.setTabOrder(self.doubleSpinBox_MaxVoltage, self.doubleSpinBox_resistance_x)
        MainWindow.setTabOrder(self.doubleSpinBox_resistance_x, self.doubleSpinBox_resistance_y)
        MainWindow.setTabOrder(self.doubleSpinBox_resistance_y, self.doubleSpinBox_resistance_z)
        MainWindow.setTabOrder(self.doubleSpinBox_resistance_z, self.pushButton_genSeq)
        MainWindow.setTabOrder(self.pushButton_genSeq, self.textBrowser_seq)
        MainWindow.setTabOrder(self.textBrowser_seq, self.textBrowser_history)
        MainWindow.setTabOrder(self.textBrowser_history, self.doubleSpinBox_SE_TE)
        MainWindow.setTabOrder(self.doubleSpinBox_SE_TE, self.checkBox_SE_is3D)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Global parameters"))
        self.label_14.setText(_translate("MainWindow", "NX"))
        self.label.setText(_translate("MainWindow", "NR"))
        self.label_2.setText(_translate("MainWindow", "N1"))
        self.label_15.setText(_translate("MainWindow", "N2"))
        self.label_16.setText(_translate("MainWindow", "S1"))
        self.label_17.setText(_translate("MainWindow", "S2"))
        self.label_18.setText(_translate("MainWindow", "DU"))
        self.label_19.setText(_translate("MainWindow", "TR"))
        self.label_20.setText(_translate("MainWindow", "DW"))
        self.label_21.setText(_translate("MainWindow", "SW"))
        self.label_22.setText(_translate("MainWindow", "OF"))
        self.label_42.setText(_translate("MainWindow", "comment"))
        __sortingEnabled = self.listWidget_G_read.isSortingEnabled()
        self.listWidget_G_read.setSortingEnabled(False)
        item = self.listWidget_G_read.item(0)
        item.setText(_translate("MainWindow", "x"))
        item = self.listWidget_G_read.item(1)
        item.setText(_translate("MainWindow", "y"))
        item = self.listWidget_G_read.item(2)
        item.setText(_translate("MainWindow", "z"))
        self.listWidget_G_read.setSortingEnabled(__sortingEnabled)
        self.label_40.setText(_translate("MainWindow", "encode1"))
        __sortingEnabled = self.listWidget_G_encode1.isSortingEnabled()
        self.listWidget_G_encode1.setSortingEnabled(False)
        item = self.listWidget_G_encode1.item(0)
        item.setText(_translate("MainWindow", "x"))
        item = self.listWidget_G_encode1.item(1)
        item.setText(_translate("MainWindow", "y"))
        item = self.listWidget_G_encode1.item(2)
        item.setText(_translate("MainWindow", "z"))
        self.listWidget_G_encode1.setSortingEnabled(__sortingEnabled)
        self.label_41.setText(_translate("MainWindow", "encode2"))
        __sortingEnabled = self.listWidget_G_encode2.isSortingEnabled()
        self.listWidget_G_encode2.setSortingEnabled(False)
        item = self.listWidget_G_encode2.item(0)
        item.setText(_translate("MainWindow", "x"))
        item = self.listWidget_G_encode2.item(1)
        item.setText(_translate("MainWindow", "y"))
        item = self.listWidget_G_encode2.item(2)
        item.setText(_translate("MainWindow", "z"))
        self.listWidget_G_encode2.setSortingEnabled(__sortingEnabled)
        self.label_39.setText(_translate("MainWindow", "read"))
        self.label_23.setText(_translate("MainWindow", "TE [ms]"))
        self.checkBox_SE_is3D.setText(_translate("MainWindow", "3D"))
        self.label_29.setText(_translate("MainWindow", "For 2D sequence, refocus grad. duration is adjusted by \"Gradient Duration Adjustment 1\""))
        self.checkBox_SE_isUD_RFPulse90.setText(_translate("MainWindow", "Use User-defined 90 RF pulse"))
        self.checkBox_SE_isUD_RFPulse180.setText(_translate("MainWindow", "Use User-defined 180 RF pulse"))
        self.tabWidget_ImageParams.setTabText(self.tabWidget_ImageParams.indexOf(self.tab_SE), _translate("MainWindow", "Spin echo"))
        self.label_33.setText(_translate("MainWindow", "TE [ms]"))
        self.checkBox_GE_is3D.setText(_translate("MainWindow", "3D"))
        self.label_34.setText(_translate("MainWindow", "For 2D sequence, refocus grad. duration is adjusted by \"Gradient Duration Adjustment 1\""))
        self.checkBox_GE_isUD_RFPulse.setText(_translate("MainWindow", "Use User-defined RF pulse"))
        self.tabWidget_ImageParams.setTabText(self.tabWidget_ImageParams.indexOf(self.tab_GE), _translate("MainWindow", "Gradient echo"))
        self.label_13.setText(_translate("MainWindow", "GZ Resistance [Ohm]"))
        self.label_12.setText(_translate("MainWindow", "GY Resistance [Ohm]"))
        self.label_11.setText(_translate("MainWindow", "GX Resistance [Ohm]"))
        self.label_6.setText(_translate("MainWindow", "Max Current [I]"))
        self.label_10.setText(_translate("MainWindow", "Max Voltage [V]"))
        self.label_25.setText(_translate("MainWindow", "Gradient Duration Adjustment 1 [us]"))
        self.label_3.setText(_translate("MainWindow", "GX [G/cm/A]"))
        self.label_4.setText(_translate("MainWindow", "GY [G/cm/A]"))
        self.label_7.setText(_translate("MainWindow", "GX Ramp [us]"))
        self.label_8.setText(_translate("MainWindow", "GY Ramp [us]"))
        self.label_5.setText(_translate("MainWindow", "GZ [G/cm/A]"))
        self.label_9.setText(_translate("MainWindow", "GZ Ramp [us]"))
        self.label_26.setText(_translate("MainWindow", "Gradient Duration Adjustment 2 [us]"))
        self.label_27.setText(_translate("MainWindow", "Gradient Duration Adjustment 3 [us]"))
        self.tabWidget_Hardware.setTabText(self.tabWidget_Hardware.indexOf(self.tab_Gradient), _translate("MainWindow", "Gradient"))
        self.pushButton_RFpulse180.setText(_translate("MainWindow", "Open (RF180)"))
        self.pushButton_RFpulse90.setText(_translate("MainWindow", "Open (RF90)"))
        self.tabWidget_Hardware.setTabText(self.tabWidget_Hardware.indexOf(self.tab_RF), _translate("MainWindow", "RF"))
        self.pushButton_genSeq.setText(_translate("MainWindow", "Generate Sequence"))
        self.pushButton_ShowEventView.setText(_translate("MainWindow", "Show SeqChart"))
        self.label_24.setText(_translate("MainWindow", "FOVr [cm]"))
        self.label_37.setText(_translate("MainWindow", "FOVe1 [cm]"))
        self.label_38.setText(_translate("MainWindow", "FOVe2 [cm]"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSaveSeq.setText(_translate("MainWindow", "Save seq"))
        self.actionSaveSeq.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen_ini_file.setText(_translate("MainWindow", "Open ini file"))
        self.actionSave_ini_file.setText(_translate("MainWindow", "Save ini file"))

